apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kafka
  namespace: testcontainers
spec:
  template:
    spec:
      metadata:
        annotations:
          # use autoscaling based on cpu resources
          # do not scale down to 0
          autoscaling.knative.dev/class: "hpa.autoscaling.knative.dev"
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.3
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.testcontainers.svc.cluster.local:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
              value: "1"
          ports:
            - containerPorts: 9092
