apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: postgresql
spec:
  template:
    spec:
      containers:
        - name: postgresql
          image: postgres:16.1
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "pass"
            - name: POSTGRES_DB
              value: "voxxeddays"
          ports:
            - containerPorts: 5432