apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: testcontainers-service
spec:
  template:
    spec:
      containers:
        - name: testcontainers-service
          image: abellmann/spring-boot-testcontainers
          ports:
            - containerPort: 8080