apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zookeeper
spec:
  template:
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.3
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181